export const products = [
  {
    id: 1,
    img: "/portfolio.png",
    link: "http://lama.dev",
    title: "Portfolio",
    desc: "il sito che stai leggendo in questo momento. Realizzato con HTML, CSS, Javascript e React.",
    tagHtml: "HTML",
    tagCss: "CSS",
    tagJavascript: "Javascript",
    tagReact: "React",
  },
  {
    id: 2,
    img: "/spaziocasa.jpg",
    link: "http://lama.dev",
    title: "Spazio Casa",
    desc: "eCommerce d'arte e di arredamento ideato su Illustrator e poi realizzato con HTML, CSS, Javascript e plugin Woocommerce per gestire la logica degli acquisti e l'archivio dei prodotti. Incluso nel progetto il copywriting delle pagine e dei prodotti.",
    tagHtml: "HTML",
    tagCss: "CSS",
    tagJavascript: "Javascript",
    tagWordpress: "Wordpress",
    tagElementor: "Elementor",
    tagAdobe: "Adobe",
  },
  {
    id: 3,
    img: "/lacicogna.jpg",
    link: "http://lama.dev",
    title: "La Cicogna",
    desc: "eCommerce d'abbigliamento e prodotti per l'infanzia ideato su Illustrator e poi realizzato con HTML, CSS, Javascript e plugin Woocommerce per gestire la logica degli acquisti e l'archivio dei prodotti. Incluso nel progetto il copywriting delle pagine e dei prodotti.",
    tagHtml: "HTML",
    tagCss: "CSS",
    tagJavascript: "Javascript",
    tagWordpress: "Wordpress",
    tagElementor: "Elementor",
    tagAdobe: "Adobe",
  },
  {
    id: 4,
    img: "/daucus.png",
    link: "http://lama.dev",
    title: "Sito vetrina illuminazione",
    desc: "Sito vetrina per prodotti di design d'illuminazione. Elaborazione del wireframe del sito web e realizzazione del design e dell'user journey su Figma.",
    tagFigma: "Figma",
  },
  {
    id: 5,
    img: "/cyclopic.png",
    link: "http://lama.dev",
    title: "Sito vetrina architettura",
    desc: "Sito vetrina per progetti di architettura e di rendering. Elaborazione del wireframe del sito web e realizzazione del design e dell'user journey su Figma.",
    tagFigma: "Figma",
  },
  {
    id: 6,
    img: "",
    link: "http://lama.dev",
  },
];
